import type { AxisVector, Question, QuestionOption } from "../../../shared/types/quiz";

function option(
  id: string,
  text: string,
  delta: AxisVector,
  tags: string[],
  resultNote: string,
): QuestionOption {
  return {
    id,
    text,
    delta,
    tags,
    resultNote,
  };
}

export const questions: Question[] = [
  {
    id: "q01",
    order: 1,
    category: "排练危机",
    prompt: "乐队排练有人迟到半小时，你下意识会怎么做？",
    sceneHint: "保留“乐队内气氛失衡”的熟悉感，但不直接复述剧情。",
    tags: ["rehearsal", "conflict", "timing"],
    options: [
      option("q01-a", "先沉默等着，反正说了也不一定会变好。", [-0.5, -0.3, -0.2], ["withdraw", "freeze"], "你习惯先吞下不满。"),
      option("q01-b", "直接开火，迟到就是不尊重大家。", [0.6, 0.4, 0.3], ["explosive", "justice"], "你会把怒气直接摆上桌。"),
      option("q01-c", "先去买个甜品，回来再看局势。", [0, -0.2, 0.5], ["freedom", "self-aware"], "你会先让自己保持舒服。"),
      option("q01-d", "打电话确认对方安全，再礼貌提醒。", [0.2, 0.5, 0.1], ["caretaker", "stabilize"], "你会先处理关系，再处理规矩。"),
    ],
  },
  {
    id: "q02",
    order: 2,
    category: "群聊空气",
    prompt: "群聊突然冷场了，你会怎么处理？",
    sceneHint: "像 LINE 群聊里朋友问你的日常选择题。",
    tags: ["group-chat", "social"],
    options: [
      option("q02-a", "假装没看到，等别人先开口。", [-0.4, -0.5, -0.1], ["avoidance", "withdraw"], "你宁可先当空气。"),
      option("q02-b", "丢个新话题，强行把气氛拉回来。", [0.5, 0.7, -0.2], ["push", "spotlight"], "你会主动把群聊拽回热闹。"),
      option("q02-c", "发个表情包，点到为止。", [0.1, 0, 0.2], ["buffer", "playful"], "你偏好轻巧试探。"),
      option("q02-d", "私聊最在意的那个人，问她是不是不开心。", [-0.2, 0.4, 0.6], ["caretaker", "self-aware"], "你更在意真正冷掉的是谁。"),
    ],
  },
  {
    id: "q03",
    order: 3,
    category: "逞强现场",
    prompt: "你发现朋友把自己逼得太狠，但她嘴上又说没事。",
    sceneHint: "保留粉丝能认出的“逞强 / 失控 / 拉扯”氛围。",
    tags: ["pressure", "care"],
    options: [
      option("q03-a", "我也不知道怎么劝，只能陪着。", [-0.3, 0, -0.2], ["quiet-support", "freeze"], "你会留下，但不会硬闯。"),
      option("q03-b", "不管她愿不愿意，先把人拽回来再说。", [0.7, 0.8, 0.2], ["push", "protect"], "你宁可粗暴也不想看她继续掉下去。"),
      option("q03-c", "我会冷静拆解问题，让她别再硬撑。", [-0.1, 0.6, 0.7], ["analysis", "control", "caretaker"], "你倾向用清醒来止血。"),
      option("q03-d", "说点轻飘飘的话缓和气氛，顺手逃避正面冲突。", [0.3, -0.6, -0.4], ["avoidance", "surface"], "你先让场面别太难看。"),
    ],
  },
  {
    id: "q04",
    order: 4,
    category: "临时换歌",
    prompt: "演出前一晚，主唱突然说想把整首歌重排。",
    sceneHint: "保留“排练室里一秒爆炸”的紧绷感。",
    tags: ["performance", "last-minute"],
    options: [
      option("q04-a", "我会先慌住，但最后还是点头配合。", [-0.4, 0.1, -0.5], ["hesitate", "follow"], "你容易被局势推着走。"),
      option("q04-b", "直接说不行，现在改就是在害大家。", [0.8, 0.3, 0.4], ["explosive", "boundary"], "你会把底线说得很响。"),
      option("q04-c", "先问她为什么想改，再判断值不值得冒险。", [-0.1, 0.4, 0.8], ["analysis", "self-aware"], "你会先确认动机，再决定站位。"),
      option("q04-d", "我来帮她拆分任务，今晚至少把最危险的部分补掉。", [0.2, 0.7, 0.5], ["caretaker", "control"], "你会把混乱转成可执行清单。"),
    ],
  },
  {
    id: "q05",
    order: 5,
    category: "被放鸽子",
    prompt: "你认真准备了一整天，对方却在最后十分钟说来不了。",
    sceneHint: "强调“被辜负”的刺痛感，但仍然是群聊问答语气。",
    tags: ["promise", "abandonment"],
    options: [
      option("q05-a", "回一句“没事”，然后自己消化。", [-0.6, -0.4, -0.3], ["withdraw", "abandonment"], "你会把委屈收回身体里。"),
      option("q05-b", "直接发一串问号，问她把我当什么。", [0.7, 0.2, 0.2], ["explosive", "abandonment"], "你会让失望立刻有声音。"),
      option("q05-c", "先判断她是不是遇到真的麻烦，再决定生不生气。", [-0.2, 0.2, 0.7], ["analysis", "self-aware"], "你想先把事实搞清。"),
      option("q05-d", "我会说理解她，但心里默默记账，下次不再全押。", [-0.1, 0.5, 0.8], ["status-guard", "abandonment"], "你会体面收场，但不会忘。"),
    ],
  },
  {
    id: "q06",
    order: 6,
    category: "误会扩散",
    prompt: "群里有人误解了你的意思，气氛开始往奇怪的方向滑。",
    sceneHint: "更像朋友局里的误会爆炸，而不是正式辩论。",
    tags: ["misunderstanding", "communication"],
    options: [
      option("q06-a", "算了，不解释了，误会就误会吧。", [-0.5, -0.7, -0.3], ["withdraw", "avoidance"], "你会优先退出战场。"),
      option("q06-b", "立刻开麦，把每个细节都对清楚。", [0.7, 0.4, 0.6], ["explosive", "clarify"], "你不接受被曲解后还保持安静。"),
      option("q06-c", "换个更轻松的说法，把大家带回安全区。", [0.1, 0.6, 0.2], ["buffer", "stabilize"], "你会先把空气压回可控。"),
      option("q06-d", "私聊当事人，确认她到底在意哪一句。", [-0.2, 0.3, 0.7], ["caretaker", "self-aware"], "你更在意误伤点在哪里。"),
    ],
  },
  {
    id: "q07",
    order: 7,
    category: "退团预告",
    prompt: "有人在演出前说“要不我还是退出吧”。",
    sceneHint: "保留 MyGO 式“临门一脚要散”的失重感。",
    tags: ["breakup", "band"],
    options: [
      option("q07-a", "脑子一片空白，先求她别走。", [-0.3, -0.1, -0.5], ["cling", "abandonment"], "你第一反应是别让关系断掉。"),
      option("q07-b", "你现在说这个是不是太不负责了？", [0.8, 0.5, 0.2], ["explosive", "justice"], "你会把愤怒当成挽留。"),
      option("q07-c", "如果她真的想走，我会先尊重，再问剩下的人怎么办。", [-0.2, 0.2, 0.9], ["self-aware", "reframe"], "你会先把现实摆稳。"),
      option("q07-d", "先把人留住，后面怎么修都行。", [0.4, 0.8, -0.2], ["push", "caretaker"], "你更怕当场散掉。"),
    ],
  },
  {
    id: "q08",
    order: 8,
    category: "被安排的人生",
    prompt: "别人已经替你决定好接下来该怎么做，还说“我是为你好”。",
    sceneHint: "强调“被定义”的不适，而不是职场鸡汤。",
    tags: ["control", "agency"],
    options: [
      option("q08-a", "嘴上答应，心里开始悄悄远离。", [-0.4, -0.6, 0], ["avoidance", "status-guard"], "你会表面配合，实际抽离。"),
      option("q08-b", "当场顶回去，我的人生不用你排。", [0.8, 0.2, 0.7], ["boundary", "explosive"], "你会立刻夺回主动权。"),
      option("q08-c", "先听完，再挑自己真正认同的部分。", [-0.1, -0.1, 0.8], ["self-aware", "filter"], "你会把外界意见拆开后再吸收。"),
      option("q08-d", "我会礼貌拒绝，但尽量不把关系撕破。", [-0.2, 0.5, 0.6], ["status-guard", "stabilize"], "你守住边界时仍想保体面。"),
    ],
  },
  {
    id: "q09",
    order: 9,
    category: "过热示好",
    prompt: "刚认识没多久的人突然对你特别热情，像已经把你写进未来计划。",
    sceneHint: "保留“好像被强行拉进羁绊”的怪异喜感。",
    tags: ["intimacy", "trust"],
    options: [
      option("q09-a", "先后退半步，观察她到底想干嘛。", [-0.4, -0.5, 0.4], ["withdraw", "self-protective"], "你不轻易让人越线。"),
      option("q09-b", "好耶，那就一起冲，我最怕冷场。", [0.6, 0.8, -0.3], ["spotlight", "push"], "你会先接住热情再说。"),
      option("q09-c", "我会温柔接住，但不承诺太快。", [-0.1, 0.3, 0.7], ["status-guard", "self-aware"], "你愿意回应，但保留判断权。"),
      option("q09-d", "发个怪表情糊弄过去，先让关系浮在半空。", [0.2, -0.4, 0.1], ["buffer", "avoidance"], "你会用玩笑挡一下亲密感。"),
    ],
  },
  {
    id: "q10",
    order: 10,
    category: "排练后争吵",
    prompt: "排练刚结束，最熟的两个人突然当着所有人吵起来了。",
    sceneHint: "需要有“谁都不想先低头”的群像拉扯感。",
    tags: ["argument", "group-dynamics"],
    options: [
      option("q10-a", "装作整理东西，等风暴自己过去。", [-0.5, -0.6, -0.2], ["withdraw", "avoidance"], "你会先保护自己不被卷进去。"),
      option("q10-b", "直接插进去，谁说话难听我就怼谁。", [0.9, 0.4, 0.3], ["explosive", "protect"], "你会在最吵的时候跳进中心。"),
      option("q10-c", "把两边的核心诉求拎出来，先停止互相乱打。", [-0.1, 0.6, 0.8], ["control", "analysis"], "你会优先整理战场规则。"),
      option("q10-d", "先带走最容易崩的那个，让另一边冷静一下。", [0.2, 0.7, 0.4], ["caretaker", "stabilize"], "你先救最危险的点。"),
    ],
  },
  {
    id: "q11",
    order: 11,
    category: "身体吃不消",
    prompt: "队友明明状态很差，还坚持说自己可以撑完今天。",
    sceneHint: "这里要有“嘴硬”和“照料”同时存在的张力。",
    tags: ["health", "care"],
    options: [
      option("q11-a", "她都这么说了，我就不再追问。", [-0.4, -0.4, -0.3], ["follow", "withdraw"], "你会尊重对方表面说法。"),
      option("q11-b", "不行就是不行，今天你必须休息。", [0.7, 0.6, 0.2], ["protect", "push"], "你会强行替她踩刹车。"),
      option("q11-c", "我会替她收掉最耗神的部分，别让她太难堪。", [-0.2, 0.6, 0.6], ["caretaker", "status-guard"], "你会一边照顾人，一边帮她保面子。"),
      option("q11-d", "先问她到底在硬撑什么，再决定怎么劝。", [-0.1, 0.2, 0.8], ["analysis", "self-aware"], "你想先找到真正卡住她的点。"),
    ],
  },
  {
    id: "q12",
    order: 12,
    category: "功劳归属",
    prompt: "一个项目被夸爆了，但大家只记得你的名字。",
    sceneHint: "测试你对体面、愧疚和掌控感的处理方式。",
    tags: ["credit", "recognition"],
    options: [
      option("q12-a", "赶紧缩起来，巴不得别再提我。", [-0.6, -0.5, -0.2], ["withdraw", "guilt"], "聚光灯会先让你想逃。"),
      option("q12-b", "立刻纠正，谁做的谁就该被看见。", [0.6, 0.3, 0.7], ["justice", "clarify"], "你不接受错误署名。"),
      option("q12-c", "先把功劳分回去，再顺手把后续安排接住。", [0.1, 0.7, 0.6], ["control", "caretaker"], "你会体面处理并顺势接盘。"),
      option("q12-d", "嘴上客气收下，心里默默记谁以后值得继续合作。", [-0.1, 0.2, 0.8], ["status-guard", "self-aware"], "你会从掌声里继续做判断。"),
    ],
  },
  {
    id: "q13",
    order: 13,
    category: "突然失联",
    prompt: "最重要的那个人说想消失几天，不想被任何人找到。",
    sceneHint: "保留“怕失去但又怕逼太紧”的复杂度。",
    tags: ["distance", "abandonment"],
    options: [
      option("q13-a", "我会尊重她，但这几天整个人都会悬着。", [-0.5, -0.2, -0.1], ["abandonment", "cling"], "你表面放手，心里却一直抓着。"),
      option("q13-b", "不行，我还是会追过去把人找回来。", [0.8, 0.7, 0.1], ["push", "abandonment", "protect"], "你最怕的是关系在沉默里断线。"),
      option("q13-c", "先留一句“我在”，再给她能回来的路径。", [-0.2, 0.4, 0.7], ["caretaker", "self-aware"], "你会留门，而不是堵门。"),
      option("q13-d", "我会回得很体面，但之后把自己的期待收回来。", [-0.1, 0.3, 0.8], ["status-guard", "abandonment"], "你不想再把脆弱押到别人手里。"),
    ],
  },
  {
    id: "q14",
    order: 14,
    category: "久别重逢",
    prompt: "很久没联系的人突然发来一句“最近还好吗”。",
    sceneHint: "更像夜里突然亮起的通知，而不是正式 reunion。",
    tags: ["reconnect", "memory"],
    options: [
      option("q14-a", "盯着消息框发呆很久，最后还是回得很轻。", [-0.5, -0.3, -0.2], ["withdraw", "nostalgia"], "你会先保护旧伤口。"),
      option("q14-b", "直接把这些年的不爽都问出来。", [0.7, 0.2, 0.4], ["explosive", "clarify"], "你不想再假装什么都没发生。"),
      option("q14-c", "我会先确认她这次回来是想寒暄，还是想修复。", [-0.2, 0.1, 0.8], ["analysis", "self-aware"], "你会先判断对方的真实意图。"),
      option("q14-d", "礼貌接住，再慢慢把聊天引到舒服的节奏。", [0, 0.6, 0.5], ["stabilize", "caretaker"], "你会先把关系放进安全框里。"),
    ],
  },
  {
    id: "q15",
    order: 15,
    category: "复盘时刻",
    prompt: "一场大混乱终于结束了，大家问你这次到底学到了什么。",
    sceneHint: "像演出后凌晨两点的群聊总结，带一点狼狈也带一点真心。",
    tags: ["reflection", "closure"],
    options: [
      option("q15-a", "学到别再把真心说得太慢。", [-0.4, -0.2, -0.1], ["reflective", "soft"], "你会把答案指向自己没说出口的部分。"),
      option("q15-b", "学到有问题就立刻炸，不然只会更糟。", [0.8, 0.1, 0.3], ["explosive", "boundary"], "你相信及时发作比闷坏更有用。"),
      option("q15-c", "学到人会变，但我至少要知道自己想守什么。", [-0.1, -0.1, 0.9], ["self-aware", "anchor"], "你最终还是会回到自己的坐标。"),
      option("q15-d", "学到关系不是放着就会好，得有人伸手去修。", [0.2, 0.7, 0.4], ["caretaker", "repair"], "你更相信修复需要主动动作。"),
    ],
  },
];
